version: "3.7"

services: 
  lms-database:
    image: mysql:latest
    ports:
    -  "8734:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=learning@1
    - MYSQL_DATABASE=learning
    restart: always
    volumes:
    - ./data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

  lms-moodle:
    image: moodlehq/moodle-php-apache:7.1
    ports: 
    - "8735:80"
    volumes:
    - ./lms:${PWD}/var/www/html
